### ISSUE TITLE
Scraper not restricted to Adelaide Hills Council

### ISSUE THREAD

**Issue by softgrow** [MichaelBone/adelaide_hills_council_sa_development_applications#1]
I got a bunch of alerts this morning that are well outside this LGA. See https://morph.io/planningalerts-scrapers/adelaide_hills_council_sa_development_applications for example see below.

It may be that it is using the applicants address rather than the address of the development.

--
17/690 | PO BOX 584, BIRDWOOD SA 5234 | Change of use to include horticulture- market garden (5.5 hectares), including change of use of existing farm building to associated agricultural industry (processing of produce) | https://www.ahc.sa.gov.au/ahc-resident/Documents/DA%20Register%20at%2009%20August%202018.pdf | mailto:mail@ahc.sa.gov.au | 2018-08-09 | 2017-08-10 |   |  
17/669 | 109A Archer Street, NORTH ADELAIDE SA 5006 | Split level detached dwelling and associated earthworks | https://www.ahc.sa.gov.au/ahc-resident/Documents/DA%20Register%20at%2009%20August%202018.pdf | mailto:mail@ahc.sa.gov.au | 2018-08-09 | 2017-08-10 |   |  
17/703 | 503 Lower North East Road, CAMPBELLTOWN, SA 5074 | Dwelling, including retaining wall (maximum height 700mm) & associated earthworks | https://www.ahc.sa.gov.au/ahc-resident/Documents/DA%20Register%20at%2009%20August%202018.pdf | mailto:mail@ahc.sa.gov.au | 2018-08-09 | 2017-08-10 |   |  
17/700 | PO BOX 42, CRAFERS SA 5152 | Carport | https://www.ahc.sa.gov.au/ahc-resident/Documents/DA%20Register%20at%2009%20August%202018.pdf | mailto:mail@ahc.sa.gov.au | 2018-08-09 | 2017-08-10 |   |  
17/705 | 86 Chinderah Bay Drive, CHINDERAH NSW 2487 | Fire hydrant | https://www.ahc.sa.gov.au/ahc-resident/Documents/DA%20Register%20at%2009%20August%202018.pdf | mailto:mail@ahc.sa.gov.au | 2018-08-09 | 2017-08-11 |   |

**Comment by MichaelBone** [comment]
This issue was corrected in commit 0508e8 (it was previously scraping the applicant postal address instead of the Property Address).
