### ISSUE TITLE
Cannot raise issues at Planning-alerts 

### ISSUE THREAD

**Issue by softgrow** [MichaelBone/adelaide_hills_council_sa_development_applications#2]
I expected to raise issue #1 at https://github.com/planningalerts-scrapers/adelaide_hills_council_sa_development_applications but the option is not available. I should be raising issues at the project level, not with the individual author.

**Comment by MichaelBone** [comment]
thanks @softgrow, that's fixed now (that "Issues" option is now available on https://github.com/planningalerts-scrapers/adelaide_hills_council_sa_development_applications).
